
version: 2

models:
    - name: laws_profile
      description: "Profile committees / Список профильных комитетов"
      columns:
          - name: law_id
            tests:
              - relationships:
                  to: ref('laws')
                  field: id
          - name: committee_id
            tests:
              - relationships:
                  to: ref('committees')
                  field: id

      order_by: (law_id,committee_id)