
version: 2

models:
    - name: votes
      description: "Votes / Список голосований"
      columns:
          - name: id
            tests:
                - unique
                - not_null
          - name: law_id
            description: "Номер законопроекта"
            tests:
              - relationships:
                  to: ref('laws')
                  field: id

          - name: date
            description: "Дата и время голосования"
          - name: subject
            description: "Тема голосования"
          - name: transcript_link
            description: "Ссылка на стенограмму голосования"
          - name: resolution
            description: "Результат голосования (true - принято, false - не принято)"
          - name: for
            description: "Число депутатов, проголосовавших <за>"
          - name: against
            description: "Число депутатов, проголосовавших <против>"
          - name: abstain
            description: "Число депутатов, проголосовавших <воздержался>"
          - name: absent
            description: "Число непроголосовавших депутатов"





      order_by: (id)
