
version: 2

models:
    - name: deputies
      description: "Gosduma deputies / Депутаты Госдумы и члены Совета Федерации"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: name
            description: "Deputy name"
          - name: is_current
            description: "Входят только в текущий созыв?"
          - name: position_id
            description: "Депутат ГД или член СФ"
            tests:
              - relationships:
                  to: ref('positions')
                  field: id
      order_by: (id)

